services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tetris-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://tetris-backend:8000
    depends_on:
      - backend
    command:
      - npx
      - vite
      - --host
      - 0.0.0.0
      - --port
      - "5173"
      - --config
      - /app/vite.config.ts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tetris-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command:
      [
        "python",
        "-m",
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
